runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.+)
  static_files: www/\1
  upload: www/(.*)

- url: /
  static_files: www/index.html
  upload: www/index.html

skip_files:
- ^node_modules*
- ^src*
- ^static*
- ^test*
- ^config*
- ^build*
- ^tmp*
- ^(.)?index.html$
- ^(.*/)?Procfile$
- ^(.*)?LICENCE$
- ^(.*/)?server.js$
- ^(.*/)?package.json$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.yaml$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
