runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /
  static_dir: build

skip_files:
- ^node_modules*
- ^src*
- ^test*
- ^config*
- ^tmp*
- ^(.)?index.html$
- ^(.*/)?Procfile$
- ^(.*)?LICENCE$
- ^(.*/)?server.js$
- ^(.*/)?package.json$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.yaml$
- ^(.*/)?.*\.map$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
